/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kyokomi' at '15/01/16 8:45' with Gradle 2.2.1
 *
 * @author kyokomi, @date 15/01/16 8:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
